### ISSUE TITLE
Gallery Submission Feedback

### ISSUE THREAD

**Issue by yeeha567** [bounce-commerce/Bounce-Commerce-Integration#1]
Hello,

We found the following issues when reviewing your GTM Gallery Submission:

Missing [categories](https://developers.google.com/tag-platform/tag-manager/templates/gallery#add_categories_to_templatetpl) in the __INFO__ section of the template.tpl.

**Comment by t-zuehlsdorff** [comment]
Fixed in 955ba2eb90e23180483a284f73476fc23da6db97 and 1f1292340fd1d9bbba8cfa1ff1da4bbe6c5b165e.

Thank you for the Feedback Sura!

**Comment by t-zuehlsdorff** [comment]
@yeeha567 What are the next steps? To review the code again or do i need to submit it again?

**Comment by yeeha567** [comment]
No need to re-submit. The PR should get approved some time later unless there are more feedbacks.

**Comment by t-zuehlsdorff** [comment]
Cool, thank you for the clarification! :)
